FROM python:3.12.0-slim

# Set author and app labels
LABEL author="Aleksander Okoń"
LABEL app="api"

# Set working directory inside the container
WORKDIR /app

# Copy requirements first to leverage caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire app directory from local PC to /app in the container
COPY container-app/ .

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"]